### ISSUE TITLE
Safer Bash Scripting

### ISSUE THREAD

**Issue by cgreene** [jperkel/nature_bash#1]
Do you want to add some of the safer bash scripting elements to these scripts? 

https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

I'm imagining that maybe someone doesn't have something installed that comes in early during one of the pipe lines or similar - it seems it'd be ideal for that to exit with an error.

**Comment by jperkel** [comment]
Thank you, @cgreene, excellent idea. If I add `set -euo pipefail`, does that mean I can safely get rid of the `if [ ! -d "$NATUREDIR" ]; then` blocks (as `cd $NATUREDIR` will fail)?

**Comment by cgreene** [comment]
I think the `set -e` part would cause it to fail - yes. It is nice to use the if statements to print the error message though. I'm imagining in some unanticipated case. Say, perhaps, someone doesn't have `git` - what does this command do?
https://github.com/jperkel/nature_bash/blob/main/04_geo.sh#L35

I think it might leave the hash blank. Then the error message that would come from the script would likely be the hash mismatch, saying that the file is corrupt. In reality, the file could be fine. Instead, you'd have to look at the earlier error message (probably something like `git: command not found`

**Comment by jperkel** [comment]
Thanks @cgreene, done!
